# Generated by Django 5.0.7 on 2024-07-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('encounter_obese', models.CharField(max_length=3)),
                ('profession_of_obese', models.CharField(max_length=255)),
                ('primary_causes_of_obesity', models.CharField(max_length=255)),
                ('junk_food_main_cause', models.CharField(max_length=3)),
                ('used_fitness_app', models.CharField(max_length=3)),
                ('fitness_apps_used', models.CharField(max_length=255)),
                ('reasons_for_app_failure', models.CharField(max_length=255)),
                ('effective_features', models.CharField(max_length=255)),
                ('barriers_to_adherence', models.CharField(max_length=255)),
                ('additional_comments', models.TextField()),
            ],
        ),
    ]
